### ISSUE TITLE
Milestone: Inform the shop about an algorithm or library it should definitely not use the way it does

### ISSUE THREAD

**Issue by julienbrs** [clementjuventin/juice-shop-ensimag#45]
Multiple exploits to patch:
- [ ] [Forge a coupon code that gives you a discount of at least 80%](https://pwning.owasp-juice.shop/companion-guide/latest/appendix/solutions.html#_forge_a_coupon_code_that_gives_you_a_discount_of_at_least_80) exploits z85 (Zero-MQ Base85 implementation) as the library for coupon codes.

- [ ]     [Solve challenge #999](https://pwning.owasp-juice.shop/companion-guide/latest/appendix/solutions.html#_solve_challenge_999) requires you to create a valid hash with the hashid library.

- [ ]     Passwords in the Users table are hashed with unsalted MD5

- [ ]     Users registering via Google account will receive a very silly default password that involves Base64 encoding.
